-- GrantMatch AI starter grant catalog seed.
-- Safe to run more than once after supabase/schema.sql has created public.grants.

insert into public.grants (
  grant_external_id,
  title,
  funder,
  description,
  eligibility,
  deadline,
  funding_amount,
  region_eligibility,
  required_documents,
  topics,
  sectors,
  source_url
)
values
  ('grant-001', 'Global Health AI Innovation Fund', 'Wellcome Applied Research Programme', 'Supports responsible AI projects that improve health outcomes in underserved communities through applied research, validation, and implementation partnerships.', 'Open to universities, research institutes, NGOs, and health technology startups with a named research lead and an implementation partner.', '2026-08-15', '$250,000 - $750,000', 'Global, with priority for LMIC implementation sites', array['Concept note', 'Budget', 'Team CVs', 'Ethics plan', 'Implementation partner letter']::text[], array['public health', 'AI diagnostics', 'health equity', 'implementation science']::text[], array['Health technology', 'Research', 'NGO']::text[], 'https://wellcome.org/grant-funding/schemes/health-ai-innovation'),
  ('grant-002', 'Climate Resilience Community Grants', 'Green Futures Foundation', 'Funds community-led climate adaptation, resilience planning, and digital tools that help vulnerable regions prepare for environmental risk.', 'Open to NGOs, local governments, universities, and social enterprises working with community stakeholders.', '2026-07-02', '$50,000 - $300,000', 'Africa, South Asia, Latin America, and small island states', array['Project plan', 'Community engagement strategy', 'Budget', 'Risk assessment']::text[], array['climate resilience', 'community data', 'adaptation', 'policy']::text[], array['Climate', 'NGO', 'Public policy']::text[], 'https://greenfutures.org/grants/community-resilience'),
  ('grant-003', 'Digital Inclusion Research Challenge', 'Open Society Technology Initiative', 'Backs research and pilot programmes that expand access to digital services, reduce exclusion, and strengthen equitable technology adoption.', 'Open to research teams, nonprofits, and startups with a measurable inclusion outcome and clear user research plan.', '2026-09-30', '$100,000 - $500,000', 'United States, Europe, and partner countries', array['Research summary', 'Impact metrics', 'Budget', 'Data protection statement']::text[], array['digital inclusion', 'equity', 'AI governance', 'user research']::text[], array['Technology', 'Research', 'Social impact']::text[], 'https://osf.org/grants/digital-inclusion'),
  ('grant-004', 'Women-Led Startup Science Fund', 'Catalyst Ventures Philanthropy', 'Provides non-dilutive funding for women-led startups translating scientific research into scalable products with public benefit.', 'Open to early-stage startups with at least one woman founder in a scientific or technical leadership role.', '2026-06-20', '$75,000 - $200,000', 'United States, Canada, United Kingdom, and European Union', array['Pitch deck', 'Use of funds', 'Founder bios', 'Market validation summary']::text[], array['commercialisation', 'startup', 'science translation', 'impact']::text[], array['Startup', 'Science', 'Technology']::text[], 'https://catalystventures.org/women-science-fund'),
  ('grant-005', 'STEM Education Access Initiative', 'Bill & Melinda Gates Foundation', 'Funds programmes that increase access to quality STEM education for learners from low-income and marginalised communities, with an emphasis on evidence-based pedagogy and teacher capacity.', 'Open to schools, universities, nonprofits, and edtech companies with demonstrated reach into underserved communities.', '2026-10-01', '$200,000 - $1,000,000', 'Sub-Saharan Africa, South Asia, Latin America, and the United States', array['Programme design', 'Learner outcome data', 'Budget narrative', 'Evaluation plan']::text[], array['education', 'STEM access', 'teacher training', 'edtech']::text[], array['Education', 'NGO', 'Technology']::text[], 'https://gatesfoundation.org/ideas/articles/stem-education'),
  ('grant-006', 'Ocean Health and Marine Conservation Fund', 'Blue Planet Foundation', 'Supports scientific research, community stewardship, and technology projects that protect marine ecosystems, combat ocean plastics, and restore coastal biodiversity.', 'Open to research institutes, conservation NGOs, and social enterprises with active marine field programmes.', '2026-07-31', '$80,000 - $400,000', 'Pacific Islands, Indian Ocean, Caribbean, and Southeast Asia', array['Field work plan', 'Species impact report', 'Budget', 'Partner letters']::text[], array['marine conservation', 'ocean plastics', 'biodiversity', 'climate science']::text[], array['Environment', 'Research', 'NGO']::text[], 'https://blueplanet.org/grants/ocean-health'),
  ('grant-007', 'Mental Health Technology Innovation Award', 'Wellcome Mental Health', 'Funds the development, testing, and scaling of digital mental health tools that improve access to evidence-based care for adolescents and young adults in under-resourced settings.', 'Open to researchers, clinicians, startups, and NGOs with a clinical or community mental health component and a named mental health professional on the team.', '2026-11-14', '$150,000 - $600,000', 'Global', array['Clinical rationale', 'User testing plan', 'Ethics approval', 'Budget']::text[], array['mental health', 'digital therapeutics', 'youth', 'access to care']::text[], array['Health technology', 'Research', 'Startup']::text[], 'https://wellcome.org/grant-funding/mental-health-innovation'),
  ('grant-008', 'Food Systems Transformation Grant', 'FAO Innovation Fund', 'Funds projects that redesign food production, distribution, and consumption systems to reduce hunger, cut emissions, and improve resilience for smallholder farmers.', 'Open to NGOs, research institutes, cooperatives, and agri-tech startups with direct engagement with smallholder or subsistence farming communities.', '2026-08-31', '$100,000 - $500,000', 'Sub-Saharan Africa, South and Southeast Asia', array['Farmer engagement plan', 'Environmental impact assessment', 'Budget', 'Sustainability model']::text[], array['food security', 'agriculture', 'climate', 'smallholder farmers']::text[], array['Agriculture', 'Climate', 'NGO']::text[], 'https://fao.org/innovation-fund/food-systems'),
  ('grant-009', 'AI Ethics and Governance Research Fund', 'Mozilla Foundation', 'Supports independent research, policy analysis, and public advocacy that shapes responsible AI governance, accountability frameworks, and bias mitigation in deployed systems.', 'Open to academic researchers, civil society organisations, and investigative journalists with a strong track record in technology policy.', '2026-09-15', '$50,000 - $250,000', 'Global', array['Research proposal', 'Dissemination strategy', 'Conflict of interest declaration', 'Budget']::text[], array['AI ethics', 'algorithmic accountability', 'governance', 'civil rights']::text[], array['Technology', 'Research', 'Public policy']::text[], 'https://foundation.mozilla.org/grants/ai-ethics'),
  ('grant-010', 'Urban Climate Adaptation Challenge', 'European Climate Foundation', 'Funds city-level projects that reduce urban heat, improve water management, retrofit building stock, and build community climate resilience in rapidly urbanising regions.', 'Open to municipal authorities, urban planning institutes, research organisations, and NGOs with a city-government partnership.', '2026-06-30', '$200,000 - $800,000', 'European Union, South and Southeast Asia, Middle East and North Africa', array['City partnership letter', 'Climate risk assessment', 'Budget', 'Monitoring plan']::text[], array['urban planning', 'climate adaptation', 'infrastructure', 'heat resilience']::text[], array['Climate', 'Public policy', 'Research']::text[], 'https://europeanclimate.org/grants/urban-adaptation'),
  ('grant-011', 'Social Enterprise Scale-Up Fund', 'Omidyar Network', 'Provides growth capital and technical assistance to social enterprises with proven models ready to expand impact across multiple geographies or demographic groups.', 'Open to registered social enterprises or impact-focused startups with at least two years of operations and evidence of measurable social outcomes.', '2026-07-15', '$300,000 - $1,500,000', 'Global', array['Impact report', 'Financial statements', 'Scale plan', 'Theory of change']::text[], array['social enterprise', 'impact investing', 'scale', 'economic development']::text[], array['Social impact', 'Startup', 'NGO']::text[], 'https://omidyar.com/grants/social-enterprise-scale'),
  ('grant-012', 'Global Journalism and Press Freedom Grant', 'Press Freedom Foundation', 'Funds investigative journalism, media safety tools, and press freedom advocacy that expose corruption, protect journalists, and strengthen public interest reporting in constrained environments.', 'Open to registered media outlets, journalism schools, and press freedom NGOs with active publishing programmes.', '2026-10-31', '$20,000 - $150,000', 'Global, with priority for restricted media environments', array['Editorial plan', 'Safety risk assessment', 'Budget', 'Journalist bios']::text[], array['journalism', 'press freedom', 'transparency', 'accountability']::text[], array['Media', 'NGO', 'Public policy']::text[], 'https://pressfreedom.org/grants/journalism'),
  ('grant-013', 'Biodiversity Data and Conservation Science Grant', 'Global Biodiversity Information Facility', 'Supports open-data projects and field research that improve species monitoring, habitat mapping, and conservation planning for threatened ecosystems.', 'Open to research institutes, natural history museums, and conservation NGOs that commit to open data publication.', '2026-08-01', '$30,000 - $200,000', 'Global', array['Data management plan', 'Species list', 'Methodology', 'Budget']::text[], array['biodiversity', 'open data', 'species monitoring', 'conservation science']::text[], array['Environment', 'Research', 'NGO']::text[], 'https://gbif.org/grants/biodiversity-data'),
  ('grant-014', 'Financial Inclusion and Economic Equity Fund', 'Bill & Melinda Gates Foundation', 'Funds fintech, savings, credit, and payment innovation that extends formal financial services to populations excluded from traditional banking systems.', 'Open to fintech startups, cooperatives, microfinance institutions, and research organisations with a verified underserved-population user base.', '2026-09-01', '$150,000 - $750,000', 'Sub-Saharan Africa, South Asia, Latin America', array['Product overview', 'User impact data', 'Financial model', 'Regulatory compliance statement']::text[], array['fintech', 'financial inclusion', 'microfinance', 'economic equity']::text[], array['Fintech', 'Social impact', 'Startup']::text[], 'https://gatesfoundation.org/ideas/articles/financial-inclusion'),
  ('grant-015', 'Indigenous Community Technology Sovereignty Grant', 'First Nations Technology Council', 'Funds digital infrastructure, data sovereignty tools, and technology programmes designed by and for Indigenous communities to strengthen cultural continuity and self-determination.', 'Open exclusively to Indigenous-led organisations, tribal councils, and Nation-owned enterprises.', '2026-11-30', '$50,000 - $300,000', 'Canada, United States, Australia, New Zealand, and Pacific Islands', array['Community mandate letter', 'Technology plan', 'Budget', 'Data sovereignty policy']::text[], array['Indigenous rights', 'digital sovereignty', 'cultural preservation', 'community data']::text[], array['Technology', 'NGO', 'Public policy']::text[], 'https://fntc.info/grants/technology-sovereignty'),
  ('grant-016', 'Renewable Energy Access Programme', 'Rockefeller Foundation', 'Funds projects that accelerate last-mile renewable energy access for off-grid communities, including solar microgrids, clean cooking solutions, and energy-efficient infrastructure.', 'Open to energy NGOs, cooperatives, and impact startups with operational experience in off-grid energy delivery.', '2026-07-20', '$200,000 - $1,000,000', 'Sub-Saharan Africa and South Asia', array['Energy access plan', 'Community agreements', 'Technical specs', 'Budget']::text[], array['renewable energy', 'energy access', 'solar', 'clean cooking']::text[], array['Energy', 'Climate', 'NGO']::text[], 'https://rockefellerfoundation.org/grants/renewable-energy'),
  ('grant-017', 'Early Childhood Development and Nutrition Research', 'UNICEF Innovation Fund', 'Supports applied research and technology pilots that improve nutrition, cognitive development, and caregiving quality for children aged 0-5 in humanitarian and low-resource settings.', 'Open to research institutes, health NGOs, and child development organisations with in-country field presence.', '2026-10-15', '$100,000 - $500,000', 'Humanitarian settings globally, low- and middle-income countries', array['Research protocol', 'Ethics approval', 'Field site agreement', 'Budget']::text[], array['early childhood', 'nutrition', 'child development', 'humanitarian']::text[], array['Health', 'NGO', 'Research']::text[], 'https://unicef.org/innovation/grants/early-childhood'),
  ('grant-018', 'Cybersecurity for Civil Society', 'Ford Foundation', 'Funds organisations that build digital security capacity, develop open-source defensive tools, and conduct research on threats targeting journalists, human rights defenders, and NGOs.', 'Open to digital security nonprofits, academic security labs, and civil society organisations with a training or tools delivery track record.', '2026-12-01', '$50,000 - $400,000', 'Global', array['Threat model', 'Programme design', 'Beneficiary list', 'Budget']::text[], array['cybersecurity', 'civil society', 'digital rights', 'open source']::text[], array['Technology', 'NGO', 'Research']::text[], 'https://fordfoundation.org/grants/cybersecurity'),
  ('grant-019', 'Antimicrobial Resistance Research Initiative', 'Wellcome Infectious Disease Programme', 'Funds discovery research, surveillance systems, and implementation science addressing antimicrobial resistance - one of the most urgent global health threats.', 'Open to universities, research institutes, and clinical networks with licensed laboratory facilities and IRB-approved protocols.', '2026-08-20', '$300,000 - $1,500,000', 'Global, with priority for endemic burden settings', array['Scientific proposal', 'Lab certification', 'Ethics approval', 'Budget justification']::text[], array['antimicrobial resistance', 'infectious disease', 'global health', 'surveillance']::text[], array['Health', 'Research', 'NGO']::text[], 'https://wellcome.org/grant-funding/infectious-disease/amr'),
  ('grant-020', 'Disability Inclusion Technology Fund', 'Disability Rights Advocacy Fund', 'Supports assistive technology development, accessible design research, and advocacy that enables people with disabilities to fully participate in digital, civic, and economic life.', 'Open to technology organisations, accessibility researchers, and disability-led NGOs. Applications must demonstrate meaningful co-design with disabled people.', '2026-09-20', '$40,000 - $250,000', 'Global', array['Co-design evidence', 'Accessibility audit', 'User testing plan', 'Budget']::text[], array['disability inclusion', 'assistive technology', 'accessible design', 'digital equity']::text[], array['Technology', 'Social impact', 'Research']::text[], 'https://draf.org/grants/disability-inclusion-tech')
on conflict (grant_external_id) do update
set
  title = excluded.title,
  funder = excluded.funder,
  description = excluded.description,
  eligibility = excluded.eligibility,
  deadline = excluded.deadline,
  funding_amount = excluded.funding_amount,
  region_eligibility = excluded.region_eligibility,
  required_documents = excluded.required_documents,
  topics = excluded.topics,
  sectors = excluded.sectors,
  source_url = excluded.source_url,
  updated_at = now();

-- Verification query: should return 20 after this seed file runs.
select count(*) as seeded_grant_count
from public.grants
where grant_external_id like 'grant-%';
